language: cpp
dist: trusty
sudo: required
group: edge

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9

    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8

    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9


    - os: linux
      compiler: clang
      env:
        - COMPILER=clang++-3.9
        - CXXFLAGS=-stdlib=libc++
        - CC=clang-3.9
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9

    - os: linux
      compiler: clang
      env:
        - COMPILER=clang++-4.0
        - CXXFLAGS=-stdlib=libc++
        - CC=clang-4.0
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0

    - os: linux
      compiler: clang
      env:
        - COMPILER=clang++-5.0
        - CXXFLAGS=-stdlib=libc++
        - CC=clang-5.0
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0

    - os: linux
      compiler: clang
      env:
        - COMPILER=clang++-6.0
        - CXXFLAGS=-stdlib=libc++
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0

    - os: linux
      compiler: clang
      env:
        - COMPILER=clang++-7
        - CXXFLAGS=-stdlib=libc++
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
            - ubuntu-toolchain-r-test
          packages:
            - clang-7

    # build on osx
    - os: osx
      osx_image: xcode8

    - os: osx
      osx_image: xcode9.4

    - os: osx
      osx_image: xcode10.3

    - os: osx
      osx_image: xcode11

script:
  # make sure CXX is correctly set
  - if [[ "${COMPILER}" != "" ]] && [[ "${TRAVIS_COMPILER}" == "gcc" ]]; then export CXX=${COMPILER}; fi

  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra -pedantic -O2" .. && make && ./aixlog_example
